name: Test Pull Request

on: push

jobs:
  test-pr:

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
#    runs-on: self-hosted

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Get cwd
        run: |
          echo "current directory: `pwd`"
          echo "GOPATH: `GOPATH`"
          echo "GITHUB_WORKSPACE: `GITHUB_WORKSPACE`"

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .

      - name: Test
        run: go test ./...
