name: Test Pull Request

on: push

jobs:
  test-pr:

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
#    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Copy project to GOPATH
        uses: ./.github/actions/copy-goroot

      - name: Change to project source directory
        run: |
          ls ${GOROOT}
          ls ${GOROOT}/src/github.com/wso2
          ls ${GOROOT}/src/github.com/wso2/information-extractor
          cd ${GOROOT}/src/github.com/wso2/information-extractor

      - name: Test
        run: go test ./...
