name: Test Pull Request

on: pull_request

jobs:
  test-pr:

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.5

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Copy project to GOROOT
        uses: ./.github/actions/copy-goroot

      - name: Change to Unix project source directory
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: cd ${GOROOT}/src/github.com/wso2/information-extractor

      - name: Change to Windows project source directory
        if: runner.os == 'Windows'
        run: cd $Env:GOROOT\\src\\github.com\\wso2\\information-extractor

      - name: Test
        run: go test ./...
