name: Test Pull Request

on: push

jobs:
  test-pr:

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

#    runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Copy project to GOPATH
        uses: ./.github/actions/copy-gopath

      - name: Get cwd
        run: |
          echo "current directory: `pwd`"
          echo "GOROOT: `echo $GOROOT`"
          echo "GITHUB_WORKSPACE: `echo $GITHUB_WORKSPACE`"

      - name: Test
        run: go test ./...
