name: Upload Executable Artifacts

on:
  push:
    branches:
      - master

jobs:
  upload-artifacts:

    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Set GOPATH
        run: |
          echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"

      - name: Checkout code
        uses: actions/checkout@v1
        with:
          path: ./src/github.com/wso2/information-extractor

      - name: Generate Artifacts
        run: make

      - uses: actions/upload-artifact@v1
        with:
          name: executable-artifacts
          path: build/target
