name: Upload Executable Artifacts

on:
  push:
    branches:
      - master

jobs:
  upload-artifacts:

    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.5

      - name: Set GOPATH
        run: |
          echo "GOPATH="$(dirname $GITHUB_WORKSPACE) >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v1
        with:
          path: ./src/github.com/wso2/information-extractor

      - name: Generate Artifacts
        id: generate_artifacts
        run: |
          ./.github/scripts/increment-version.sh ${{ secrets.GITHUB_TOKEN }}
          echo "##[set-output name=version;]$(make version)"
          make

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.generate_artifacts.outputs.version }}
          release_name: Information Extractor ${{ steps.generate_artifacts.outputs.version }} Released!

      - uses: actions/upload-artifact@v2
        with:
          name: executable-artifacts
          path: build/target
