name: Upload Executable Artifacts

on:
  push:
    branches:
      - master

jobs:
  upload-artifacts:

    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Set GOPATH
        run: |
          echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"

      - name: Checkout code
        uses: actions/checkout@v1
        with:
          path: ./src/github.com/wso2

#      - name: Copy project to GOROOT
#        uses: ./.github/actions/copy-goroot

#      - name: Change to project source directory
#        id: change_source
#        run: |
#          cd ${GOROOT}/src/github.com/wso2/information-extractor
#          echo "##[set-output name=project_source;] \
#            $(pwd)"

      - name: Generate Artifacts
        run: ./scripts/build.sh -t information-extractor -v 1.0.0 -f

      - uses: actions/upload-artifact@v1
        with:
          name: executable-artifacts
          path: build/target
#          path: ${{ steps.change_source.outputs.project_source }}/build/target